url: http://snikitin.me
title: Sergey Niktin Blog
description: 'Description my blog...'
author: Sergey Nikitin
email: snikitin.me@gmail.com
tagNames:
  css: CSS
  html: HTML
  javascript: JavaScript
  thoughts: Thoughts
  tools: Tools